[package]
name = "mascal-lsp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
serde_json = "1.0.78"
tokio = { version = "1.17.0", features = ["full"] }
tower-lsp = { version = "0.20.0", features = ["proposed"]}
serde = { version = "1.0", features = ["derive"] }
dashmap = "6.1.0"
log = "0.4.14"
mascal = { path = "../../parser" }

